project:
  type: website
  output-dir: docs

website:
  title: "Dion Ko | Personal Website"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: experience.qmd
        text: Experience
      - href: skills.qmd
        text: Skills & Education
      - href: reflection.qmd
        text: GenAI Reflection
  page-footer:
    center: 
      - text: "© 2025 Dion Ko | Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    code-copy: true
    code-tools: true
    highlight-style: github